/*
   ITSPA3 - Group 2
   Excecutive Books Inventory Form

*/
package executivebooks;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fuaad
 */
public class Inventory extends javax.swing.JFrame {
    
    Connection cn ;
    
    /**
     * Creates new form Inventory
     */
    public Inventory() {
        
        initComponents();
        
        loadData(tblInventory) ;
        
        txtId.setText("0");
        txtTitle.setText("");
        txtAuthor.setText("");
        txtPrice.setText("");
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        
    }
    
    public Inventory( String data )
    {
        
        initComponents() ;
        this.setLocationRelativeTo(null) ;
        
        connection() ;
        
        lblUser.setText(data) ;
        
        loadData(tblInventory) ;
        
        txtId.setText("0");
        txtTitle.setText("");
        txtAuthor.setText("");
        txtPrice.setText("");
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblLoggedIn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        lblAuthor = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblBookName = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblInventory = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblBgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setText("username");
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 12, -1, -1));

        jPanel1.setOpaque(false);

        btnSave.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        lblLoggedIn.setBackground(new java.awt.Color(255, 255, 255));
        lblLoggedIn.setForeground(new java.awt.Color(204, 204, 204));
        lblLoggedIn.setText("Logged in as:");
        jPanel2.add(lblLoggedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 83, -1));

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Title", "Author", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventory.setOpaque(false);
        tblInventory.getTableHeader().setReorderingAllowed(false);
        tblInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventory);
        if (tblInventory.getColumnModel().getColumnCount() > 0) {
            tblInventory.getColumnModel().getColumn(0).setResizable(false);
            tblInventory.getColumnModel().getColumn(0).setPreferredWidth(1);
            tblInventory.getColumnModel().getColumn(1).setResizable(false);
            tblInventory.getColumnModel().getColumn(2).setResizable(false);
            tblInventory.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 710, 230));

        jPanel3.setOpaque(false);

        lblAuthor.setBackground(new java.awt.Color(255, 255, 255));
        lblAuthor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAuthor.setForeground(new java.awt.Color(204, 204, 204));
        lblAuthor.setText("Author:");

        lblPrice.setBackground(new java.awt.Color(255, 255, 255));
        lblPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(204, 204, 204));
        lblPrice.setText("Price");

        lblBookName.setBackground(new java.awt.Color(255, 255, 255));
        lblBookName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblBookName.setForeground(new java.awt.Color(204, 204, 204));
        lblBookName.setText("Title:");

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(204, 204, 204));
        txtId.setText("0");

        lblID1.setBackground(new java.awt.Color(255, 255, 255));
        lblID1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblID1.setForeground(new java.awt.Color(204, 204, 204));
        lblID1.setText("ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblBookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                    .addComponent(lblID1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTitle)
                    .addComponent(txtAuthor)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId)
                    .addComponent(lblID1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookName)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthor)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblInventory.setBackground(new java.awt.Color(255, 255, 255));
        lblInventory.setFont(new java.awt.Font("Rockwell", 1, 56)); // NOI18N
        lblInventory.setForeground(new java.awt.Color(204, 204, 204));
        lblInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventory.setText("INVENTORY");
        jPanel2.add(lblInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 759, 60));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 580));

        lblBgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/executivebooks/book_shelf.jpg"))); // NOI18N
        getContentPane().add(lblBgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        Main Form = new Main(lblUser.getText()) ;
        Form.setVisible(true);
        Form.setLocationRelativeTo(null) ;
        
        this.dispose() ;
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        connection();
        
        String bTitle = txtTitle.getText();
        String bAuthor = txtAuthor.getText();
        String bPrice = txtPrice.getText();
        
        try{
            PreparedStatement ps = cn.prepareStatement("insert into inventory (Title, Author, Price)values(?,?,?)");
            ps.setString(1, bTitle);
            ps.setString(2, bAuthor);
            ps.setString(3, bPrice);
            
            ps.execute();
            
            loadData(tblInventory);
            
            cn.close();
            
            JOptionPane.showMessageDialog(null, "Saved successfully");
            txtTitle.setText("");
            txtAuthor.setText("");
            txtPrice.setText("");
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        connection();
        
        try{
            
            String id = txtId.getText();
            String bTitle = txtTitle.getText();
            String bAuthor = txtAuthor.getText();
            String price = txtPrice.getText();
            
            PreparedStatement ps = cn.prepareStatement("update inventory set Title= '"+bTitle+"', Author= '"+bAuthor+"', Price = '"+price+"' where id like '"+id+"' ");
            ps.execute();
            
            cn.close();
            
            JOptionPane.showMessageDialog(null, "Updated successfully");
            loadData ( tblInventory );
            
            txtId.setText("0");
            txtAuthor.setText("");
            txtPrice.setText("");
            txtPrice.setText("");
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());     
        }        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventoryMouseClicked
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        
        int rowIndex = tblInventory.getSelectedRow();
        
        txtId.setText(tblInventory.getValueAt(rowIndex, 0).toString());
        txtTitle.setText(tblInventory.getValueAt(rowIndex, 1).toString());
        txtAuthor.setText(tblInventory.getValueAt(rowIndex, 2).toString());
        txtPrice.setText(tblInventory.getValueAt(rowIndex, 3).toString());
        
    }//GEN-LAST:event_tblInventoryMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        txtId.setText("0");
        txtTitle.setText("");
        txtAuthor.setText("");
        txtPrice.setText("");
    
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        connection();
        
        try{
         
            String id = txtId.getText();
            
            if (id.equals("0"))
            {
                
                JOptionPane.showMessageDialog(null, "Nothing selected");
                
            }
            
            else
            {
               
               PreparedStatement ps = cn.prepareStatement("delete from inventory where id like '"+id+"' ");
               
               ps.execute();
               cn.close();
               
               JOptionPane.showMessageDialog(null, "Deleted successfully");
               
               loadData(tblInventory);
               
               txtId.setText("0");
               txtTitle.setText("");
               txtAuthor.setText("");
               txtPrice.setText("");
               
            }
       
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }
    
    public void connection()
    {
        
        try
        {
            
            Class.forName("com.mysql.jdbc.Driver") ;
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookstore", "root", "") ;
                        
        }
        catch (Exception ex)
        {
            
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
        
    }
    
    public void loadData(JTable table) 
    {
        
        try
        {
            
            connection() ;
            
            PreparedStatement pStat = cn.prepareStatement("Select * from inventory") ;
            ResultSet rSet = pStat.executeQuery() ;
            
            DefaultTableModel tblModel = (DefaultTableModel)table.getModel() ;
            
            tblModel.setRowCount(0) ;
            
            Object [] row ;
            
            while(rSet.next())
            {
                
                row = new Object[4] ;
                
                row [0] = rSet.getInt(1) ;
                row [1] = rSet.getString(2) ;
                row [2] = rSet.getString(3) ;
                row [3] = rSet.getInt(4) ;
                
                tblModel.addRow( row ) ; 
                
            }
            
            cn.close() ;
            
        }
        
        catch (Exception ex)
        {
            
            JOptionPane.showMessageDialog(null, ex.getMessage()) ;
            
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblBgImage;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblLoggedIn;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
